name: loan_advisor
description: Flutter application for calculating house, car, and personal loan payments
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/images/
  
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Light.ttf
          weight: 300
        - asset: assets/fonts/Kanit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kanit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700

# Flutter Launcher Icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon_512.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
