version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: loan-advisor-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: loan-advisor
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - loan-advisor-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loan-advisor-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/loan-advisor
      JWT_SECRET: loan-advisor-secret-key-change-in-production
      JWT_EXPIRES_IN: 7d
    depends_on:
      - mongodb
    networks:
      - loan-advisor-network

volumes:
  mongodb_data:

networks:
  loan-advisor-network:
    driver: bridge
