#
# DigitalOcean App Platform Configuration
# This file enables one-click deployment to DigitalOcean
# Starting at $5/month for the Basic tier
#
spec:
  name: loan-advisor-backend
  region: sgp
  
  # Database - MongoDB (Starting at $15/month for managed DB)
  # Alternative: Use MongoDB Atlas free tier or external MongoDB
  databases:
    - name: mongodb
      engine: MONGODB
      version: "7"
      production: false
      cluster_name: loan-advisor-db

  # Backend Service - Node.js API ($5/month Basic tier)
  services:
    - name: api
      # Deployment source
      github:
        repo: somkheartk/loan-advisor
        branch: main
        deploy_on_push: true
      
      # Build configuration
      source_dir: /backend
      build_command: npm ci && npm run build
      
      # Runtime configuration
      run_command: npm run start:prod
      
      # Environment configuration
      environment_slug: node-js
      
      # Instance configuration - Basic tier ($5/month)
      # Basic: 512MB RAM, 1 vCPU
      instance_count: 1
      instance_size_slug: basic-xxs
      
      # HTTP configuration
      http_port: 3000
      
      # Health check
      health_check:
        http_path: /health
        initial_delay_seconds: 10
        period_seconds: 10
        timeout_seconds: 5
        success_threshold: 1
        failure_threshold: 3
      
      # Environment variables
      envs:
        - key: NODE_ENV
          value: production
        - key: PORT
          value: "3000"
        - key: MONGODB_URI
          scope: RUN_TIME
          type: SECRET
          value: ${mongodb.DATABASE_URL}
        - key: JWT_SECRET
          scope: RUN_TIME
          type: SECRET
          # Set this in DigitalOcean App Platform dashboard
        - key: JWT_EXPIRES_IN
          value: "7d"
      
      # Routes
      routes:
        - path: /
